In [45]:
import numpy as np
import pandas as pd
import matplotlib as mpl

def solvepoisson(n):
    #Solves 2D Poisson Eqn with Dirichlet Boundary Conditions
    #Assembles the system matrix and right hand side
    h = 1.0 / n #Set up grid
    N = np.power((n+1),2)
    x = np.multiply(h,np.arange(0,n+1))
    y = x
    
    uexact = lambda (x,y) : np.divide(np.exp((-4.*np.power((x-0.3),2))),np.exp(9.*np.power((y-0.6),2))) #Exact Solution
    g = uexact #Solution at Boundaries = Exact Solution
    f = lambda (x,y) : np.multiply(np.exp(((-4.*np.power((x-0.3),2)) - (9.*np.power((y-0.6),2)))), (26. - np.power(((18.*y-10.8)),2)-np.power((8.*x-2.4),2))) #LHS
    
    umap = np.reshape(np.arange(1,N+1),(n+1,n+1))
    A = np.zeros((N,N))
    b = np.zeros((N,1))
    
    for j in range(0,n+1):
        for i in range(0,n+1):
            row = umap[i,j]
            if i == 0 or i == n or j == 0 or j == n: #Applies Dirichlet BC at Walls
                A[row,row] = 1.0
                b[row] = g([x[i],y[j]])
            else:
                A[row,row] = 4.0
                A[row,umap[i+1,j]] = -1.0
                A[row,umap[i-1,j]] = -1.0
                A[row,umap[i,j+1]] = -1.0
                A[row,umap[i,j-1]] = -1.0
                print f((i,j))
                #b[row] = f([x[i],y[j]])*h^2 
    return A,b

In [40]:
uexact = lambda (x,y) : np.exp((-4.*np.power((x-0.3),2)) - (9.*np.power((y-0.6),2)))  #Exact Solution
print(uexact([1.,3.]))

f = lambda (x,y) : np.multiply(np.exp(((-4.*np.power((x-0.3),2)) - (9.*np.power((y-0.6),2)))), (26. - np.power(((18.*y-10.8)),2)-np.power((8.*x-2.4),2)))
print(f((1.,2.)))

4.314762281641501e-24
-1.9691530748872695e-06


In [ ]:
n = 2
h = 1.0/n
x = np.multiply(h,np.arange(0,n+1))
y = x

N = np.power((n+1),2)

umap = np.reshape(np.arange(0,N),(n+1,n+1)).transpose()
A = np.zeros((N,N))
b = np.zeros((N,1))


for j in range(0,n+1):
    for i in range(0,n+1):
        row = umap[i,j]
        if i == 0 or i == n or j == 0 or j == n:
            A[row,row] = 1.0
            b[row] = g[x[i],y[j]]
        else:
            print("hi",row)
            A[row,row] = 4.0
            A[row,umap[i+1,j]] = -1.0
            A[row,umap[i-1,j]] = -1.0
            A[row,umap[i,j+1]] = -1.0
            A[row,umap[i,j-1]] = -1.0
            b[row] = f[x[i],y[j]]*h^2

            

In [8]:
print(umap)
A_prime = pd.DataFrame(A)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [59]:
A_prime


0    1    2    3    4    5    6    7    8
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
4  0.0 -1.0  0.0 -1.0  4.0 -1.0  0.0 -1.0  0.0
5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [44]:
solvepoisson(100)

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''