In [6]:
import numpy as np
import pandas as pd
import matplotlib as mpl

def assemblepoission(n,f,g):
    #Assembles the system matrix and right hand side
    h = 1.0 / n
    N = np.power((n+1),2)
    x = np.multiply(h,np.arange(0,n+1))
    y = x
    
    umap = np.reshape(np.arange(1,N+1),(n+1,n+1))
    A = np.zeros(N,N)
    b = np.zeros(N,1)
    
    for j in range(0,n+1):
        for i in range(0,n+1):
            row = umap(i,j)
            if i == 0 or i == n or j == 0 or j == n:
                A(row,row) = 1
                b(row) = g(x(i),y(j))
                
                
    

In [57]:
n = 2
h = 1.0/n
x = np.multiply(h,np.arange(0,n+1))
y = x

N = np.power((n+1),2)

umap = np.reshape(np.arange(0,N),(n+1,n+1)).transpose()
A = np.zeros((N,N))
b = np.zeros((N,1))


for j in range(0,n+1):
    for i in range(0,n+1):
        row = umap[i,j]
        if i == 0 or i == n or j == 0 or j == n:
            A[row,row] = 1.0
            #b(row) = g(x(i),y(j))
        else:
            print("hi",row)
            A[row,row] = 4.0
            A[row,umap[i+1,j]] = -1.0
            A[row,umap[i-1,j]] = -1.0
            A[row,umap[i,j+1]] = -1.0
            A[row,umap[i,j-1]] = -1.0
            #b[row] = f(x(i),y(j))*h^2

            

('hi', 4)


In [58]:
print(umap)
A_prime = pd.DataFrame(A)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [59]:
A_prime


0    1    2    3    4    5    6    7    8
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
4  0.0 -1.0  0.0 -1.0  4.0 -1.0  0.0 -1.0  0.0
5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0